project_name: photo_id_resizer
build:
  main: .
  binary: photo_id_resizer
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
  goarm:
      - 7
archives:
    - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
      format: tar.xz
      format_overrides:
        - goos: windows
          format: zip
      replacements:
          darwin: macOS
      wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_checksums.txt"
release:
  draft: true
